name: GitHub Actions Demo
run-name: Repo Size 🚀
on: [push]
jobs:
  RepoSize:
    name: Repository Size
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Echo branch name
      run: echo "Branch Name : ${{ github.ref_name }}"
    - name: Repo Size
      run: du -skh --exclude=".git"
      
